# Generated by Django 4.2.7 on 2023-11-08 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(verbose_name='name')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorten', models.CharField(max_length=30, verbose_name='shorten link')),
                ('url', models.TextField(verbose_name='original url')),
            ],
            options={
                'verbose_name': 'ShortLink',
                'verbose_name_plural': 'ShortLinks',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='image')),
                ('status', models.CharField(choices=[('PUBLISH', 'Publish'), ('UNPUBLISH', 'Unpublish'), ('DRAFT', 'Draft')], default='DRAFT', max_length=9)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='home.category', verbose_name='category')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='publisher')),
            ],
        ),
    ]
